In [1]:
import pandas as pd
import numpy as np
from datetime import datetime
import csv
import os 
import matplotlib.pyplot as plt
import seaborn as sns
import statsmodels.api as sm
from statsmodels.iolib.summary2 import summary_col

In [2]:
stats_df = pd.read_csv("Stats.csv")
stats_df["ZIP"] = stats_df["ZIP"].astype(str).str.zfill(5)
stats_df.set_index("ZIP", inplace=True)
stats_df

,Min Share,Black Share,White Share,Asian Share,Hisp Share,Native Share,W_Avg Emp Min Share,W_Avg Emp Black Share,W_Avg Emp White Share,W_Avg Emp Asian Share,...,Loans per Emp Bus_1,Avg Loan Amt per Emp_1,Loans per Emp Bus_2,Avg Loan Amt per Emp_2,Loans per Emp Bus_3,Avg Loan Amt per Emp_3,Rural,Avg Loan Amt per Emp_2 Adj,Avg Loan Amt per Emp_3 Adj,Census Region
ZIP,,,,,,,,,,,,,,,,,,,,,
01001,0.153910,0.020784,0.001354,0.028910,0.067711,0.846090,0.104759,0.018225,0.799004,NaN,...,0.245833,3352.367207,0.245833,902.597423,0.239583,1601.181785,0.009656,984.395315,1964.191364,Northeast
01002,0.367189,0.050403,0.001669,0.157123,0.099028,0.632811,NaN,NaN,0.801804,NaN,...,0.145798,1715.197631,0.202401,1359.536721,0.221269,1381.447152,0.149721,1482.744737,1694.639916,Northeast
01003,0.395684,0.066249,0.001056,0.201766,0.087376,0.604316,0.069946,NaN,0.792399,0.044714,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Northeast
01005,0.090816,0.009388,0.001429,0.006122,0.031224,0.909184,0.094359,0.008223,0.831570,0.069017,...,0.132075,2280.721763,0.106918,704.397612,0.125786,1318.133737,1.000000,768.233646,1616.972493,Northeast
01007,0.133113,0.017441,0.000389,0.023796,0.042793,0.866887,0.069946,NaN,0.792399,0.044714,...,0.175896,2655.974900,0.172638,1852.649565,0.185668,2044.624220,0.719704,2020.545932,2508.168199,Northeast
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99923,0.106061,0.000000,0.000000,0.000000,0.030303,0.893939,NaN,NaN,0.800000,NaN,...,0.000000,0.000000,0.250000,496.363636,0.000000,0.000000,1.000000,541.346591,0.000000,West
99925,0.626276,0.005102,0.440051,0.010204,0.017857,0.373724,NaN,NaN,0.800000,NaN,...,0.066667,1121.355378,0.100000,1836.290837,0.166667,2622.490040,1.000000,2002.704694,3217.044021,West
99926,0.903329,0.002561,0.743278,0.000000,0.029449,0.096671,NaN,NaN,0.800000,NaN,...,0.000000,0.000000,0.083333,895.882353,0.000000,0.000000,1.000000,977.071691,0.000000,West
99927,0.142857,0.000000,0.000000,0.000000,0.040816,0.857143,NaN,NaN,0.800000,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,West
99929,0.364598,0.000000,0.173641,0.012025,0.036075,0.635402,NaN,NaN,0.810526,NaN,...,0.294737,1062.297637,0.284211,1539.648819,0.652632,4324.713376,1.000000,1679.179493,5305.184422,West

In [3]:
df = pd.read_csv("nhgis0004_ds254_20215_zcta.csv")
df["ZIP"] = df["GISJOIN"].astype(str).str[1:]
df.set_index("ZIP", inplace=True)
df

,GISJOIN,YEAR,STUSAB,REGIONA,DIVISIONA,STATEA,COUNTYA,COUSUBA,PLACEA,TRACTA,...,PCI,PUMAA,GEO_ID,BTTRA,BTBGA,TL_GEO_ID,NAME_E,AORME001,NAME_M,AORMM001
ZIP,,,,,,,,,,,,,,,,,,,,,
00601,G00601,2017-2021,PR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,860Z200US00601,NaN,NaN,601,ZCTA5 00601,7587.0,ZCTA5 00601,639.0
00602,G00602,2017-2021,PR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,860Z200US00602,NaN,NaN,602,ZCTA5 00602,10699.0,ZCTA5 00602,609.0
00603,G00603,2017-2021,PR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,860Z200US00603,NaN,NaN,603,ZCTA5 00603,12280.0,ZCTA5 00603,930.0
00606,G00606,2017-2021,PR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,860Z200US00606,NaN,NaN,606,ZCTA5 00606,8574.0,ZCTA5 00606,883.0
00610,G00610,2017-2021,PR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,860Z200US00610,NaN,NaN,610,ZCTA5 00610,11638.0,ZCTA5 00610,872.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99923,G99923,2017-2021,US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,860Z200US99923,NaN,NaN,99923,ZCTA5 99923,NaN,ZCTA5 99923,NaN
99925,G99925,2017-2021,US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,860Z200US99925,NaN,NaN,99925,ZCTA5 99925,30746.0,ZCTA5 99925,4725.0
99926,G99926,2017-2021,US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,860Z200US99926,NaN,NaN,99926,ZCTA5 99926,24979.0,ZCTA5 99926,3317.0
99927,G99927,2017-2021,US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,860Z200US99927,NaN,NaN,99927,ZCTA5 99927,NaN,ZCTA5 99927,NaN
99929,G99929,2017-2021,US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,860Z200US99929,NaN,NaN,99929,ZCTA5 99929,31080.0,ZCTA5 99929,3370.0

In [4]:
stats_df["PC Inc"] = df["AORME001"]
stats_df

,Min Share,Black Share,White Share,Asian Share,Hisp Share,Native Share,W_Avg Emp Min Share,W_Avg Emp Black Share,W_Avg Emp White Share,W_Avg Emp Asian Share,...,Avg Loan Amt per Emp_1,Loans per Emp Bus_2,Avg Loan Amt per Emp_2,Loans per Emp Bus_3,Avg Loan Amt per Emp_3,Rural,Avg Loan Amt per Emp_2 Adj,Avg Loan Amt per Emp_3 Adj,Census Region,PC Inc
ZIP,,,,,,,,,,,,,,,,,,,,,
01001,0.153910,0.020784,0.001354,0.028910,0.067711,0.846090,0.104759,0.018225,0.799004,NaN,...,3352.367207,0.245833,902.597423,0.239583,1601.181785,0.009656,984.395315,1964.191364,Northeast,41144.0
01002,0.367189,0.050403,0.001669,0.157123,0.099028,0.632811,NaN,NaN,0.801804,NaN,...,1715.197631,0.202401,1359.536721,0.221269,1381.447152,0.149721,1482.744737,1694.639916,Northeast,38627.0
01003,0.395684,0.066249,0.001056,0.201766,0.087376,0.604316,0.069946,NaN,0.792399,0.044714,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Northeast,4935.0
01005,0.090816,0.009388,0.001429,0.006122,0.031224,0.909184,0.094359,0.008223,0.831570,0.069017,...,2280.721763,0.106918,704.397612,0.125786,1318.133737,1.000000,768.233646,1616.972493,Northeast,39783.0
01007,0.133113,0.017441,0.000389,0.023796,0.042793,0.866887,0.069946,NaN,0.792399,0.044714,...,2655.974900,0.172638,1852.649565,0.185668,2044.624220,0.719704,2020.545932,2508.168199,Northeast,43450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99923,0.106061,0.000000,0.000000,0.000000,0.030303,0.893939,NaN,NaN,0.800000,NaN,...,0.000000,0.250000,496.363636,0.000000,0.000000,1.000000,541.346591,0.000000,West,NaN
99925,0.626276,0.005102,0.440051,0.010204,0.017857,0.373724,NaN,NaN,0.800000,NaN,...,1121.355378,0.100000,1836.290837,0.166667,2622.490040,1.000000,2002.704694,3217.044021,West,30746.0
99926,0.903329,0.002561,0.743278,0.000000,0.029449,0.096671,NaN,NaN,0.800000,NaN,...,0.000000,0.083333,895.882353,0.000000,0.000000,1.000000,977.071691,0.000000,West,24979.0
99927,0.142857,0.000000,0.000000,0.000000,0.040816,0.857143,NaN,NaN,0.800000,NaN,...,NaN,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,West,NaN
99929,0.364598,0.000000,0.173641,0.012025,0.036075,0.635402,NaN,NaN,0.810526,NaN,...,1062.297637,0.284211,1539.648819,0.652632,4324.713376,1.000000,1679.179493,5305.184422,West,31080.0

In [5]:
df = pd.read_csv("nhgis0004_ds255_20215_zcta.csv")
df["ZIP"] = df["GISJOIN"].astype(str).str[1:]
df.set_index("ZIP", inplace=True)
df

,GISJOIN,YEAR,STUSAB,REGIONA,DIVISIONA,STATEA,COUNTYA,COUSUBA,PLACEA,TRACTA,...,PCI,PUMAA,GEO_ID,BTTRA,BTBG,TL_GEO_ID,NAME_E,AO72E001,NAME_M,AO72M001
ZIP,,,,,,,,,,,,,,,,,,,,,
00601,G00601,2017-2021,PR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,860Z200US00601,NaN,NaN,601,ZCTA5 00601,0.4490,ZCTA5 00601,0.0272
00602,G00602,2017-2021,PR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,860Z200US00602,NaN,NaN,602,ZCTA5 00602,0.4926,ZCTA5 00602,0.0170
00603,G00603,2017-2021,PR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,860Z200US00603,NaN,NaN,603,ZCTA5 00603,0.5702,ZCTA5 00603,0.0256
00606,G00606,2017-2021,PR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,860Z200US00606,NaN,NaN,606,ZCTA5 00606,0.4373,ZCTA5 00606,0.0327
00610,G00610,2017-2021,PR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,860Z200US00610,NaN,NaN,610,ZCTA5 00610,0.4640,ZCTA5 00610,0.0285
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99923,G99923,2017-2021,US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,860Z200US99923,NaN,NaN,99923,ZCTA5 99923,NaN,ZCTA5 99923,NaN
99925,G99925,2017-2021,US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,860Z200US99925,NaN,NaN,99925,ZCTA5 99925,0.4480,ZCTA5 99925,0.0452
99926,G99926,2017-2021,US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,860Z200US99926,NaN,NaN,99926,ZCTA5 99926,0.3818,ZCTA5 99926,0.0345
99927,G99927,2017-2021,US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,860Z200US99927,NaN,NaN,99927,ZCTA5 99927,NaN,ZCTA5 99927,NaN
99929,G99929,2017-2021,US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,860Z200US99929,NaN,NaN,99929,ZCTA5 99929,0.4146,ZCTA5 99929,0.0321

In [6]:
stats_df["Gini"] = df["AO72E001"]
stats_df

,Min Share,Black Share,White Share,Asian Share,Hisp Share,Native Share,W_Avg Emp Min Share,W_Avg Emp Black Share,W_Avg Emp White Share,W_Avg Emp Asian Share,...,Loans per Emp Bus_2,Avg Loan Amt per Emp_2,Loans per Emp Bus_3,Avg Loan Amt per Emp_3,Rural,Avg Loan Amt per Emp_2 Adj,Avg Loan Amt per Emp_3 Adj,Census Region,PC Inc,Gini
ZIP,,,,,,,,,,,,,,,,,,,,,
01001,0.153910,0.020784,0.001354,0.028910,0.067711,0.846090,0.104759,0.018225,0.799004,NaN,...,0.245833,902.597423,0.239583,1601.181785,0.009656,984.395315,1964.191364,Northeast,41144.0,0.4284
01002,0.367189,0.050403,0.001669,0.157123,0.099028,0.632811,NaN,NaN,0.801804,NaN,...,0.202401,1359.536721,0.221269,1381.447152,0.149721,1482.744737,1694.639916,Northeast,38627.0,0.5444
01003,0.395684,0.066249,0.001056,0.201766,0.087376,0.604316,0.069946,NaN,0.792399,0.044714,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,Northeast,4935.0,0.5023
01005,0.090816,0.009388,0.001429,0.006122,0.031224,0.909184,0.094359,0.008223,0.831570,0.069017,...,0.106918,704.397612,0.125786,1318.133737,1.000000,768.233646,1616.972493,Northeast,39783.0,0.3377
01007,0.133113,0.017441,0.000389,0.023796,0.042793,0.866887,0.069946,NaN,0.792399,0.044714,...,0.172638,1852.649565,0.185668,2044.624220,0.719704,2020.545932,2508.168199,Northeast,43450.0,0.3815
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99923,0.106061,0.000000,0.000000,0.000000,0.030303,0.893939,NaN,NaN,0.800000,NaN,...,0.250000,496.363636,0.000000,0.000000,1.000000,541.346591,0.000000,West,NaN,NaN
99925,0.626276,0.005102,0.440051,0.010204,0.017857,0.373724,NaN,NaN,0.800000,NaN,...,0.100000,1836.290837,0.166667,2622.490040,1.000000,2002.704694,3217.044021,West,30746.0,0.4480
99926,0.903329,0.002561,0.743278,0.000000,0.029449,0.096671,NaN,NaN,0.800000,NaN,...,0.083333,895.882353,0.000000,0.000000,1.000000,977.071691,0.000000,West,24979.0,0.3818
99927,0.142857,0.000000,0.000000,0.000000,0.040816,0.857143,NaN,NaN,0.800000,NaN,...,NaN,NaN,NaN,NaN,1.000000,NaN,NaN,West,NaN,NaN
99929,0.364598,0.000000,0.173641,0.012025,0.036075,0.635402,NaN,NaN,0.810526,NaN,...,0.284211,1539.648819,0.652632,4324.713376,1.000000,1679.179493,5305.184422,West,31080.0,0.4146

In [7]:
df = pd.read_csv("nhgis0005_ds254_20215_zcta.csv")
df["ZIP"] = df["GISJOIN"].astype(str).str[1:]
df.set_index("ZIP", inplace=True)
df

,GISJOIN,YEAR,STUSAB,REGIONA,DIVISIONA,STATEA,COUNTYA,COUSUBA,PLACEA,TRACTA,...,AOT9E001,NAME_M,AOSJM001,AOSJM002,AOSJM003,AOSJM004,AOSJM005,AOSJM006,AOSJM007,AOT9M001
ZIP,,,,,,,,,,,,,,,,,,,,,
00601,G00601,2017-2021,PR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,377.0,ZCTA5 00601,361,493,493,394,394,24,460,18.0
00602,G00602,2017-2021,PR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,414.0,ZCTA5 00602,312,724,724,762,278,32,771,23.0
00603,G00603,2017-2021,PR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,409.0,ZCTA5 00603,788,825,815,766,365,55,845,43.0
00606,G00606,2017-2021,PR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,350.0,ZCTA5 00606,329,274,274,241,131,21,310,60.0
00610,G00610,2017-2021,PR,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,478.0,ZCTA5 00610,388,573,573,602,290,28,622,50.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99923,G99923,2017-2021,US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,ZCTA5 99923,20,20,20,20,10,10,10,NaN
99925,G99925,2017-2021,US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,794.0,ZCTA5 99925,91,71,71,66,21,10,47,71.0
99926,G99926,2017-2021,US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,600.0,ZCTA5 99926,104,79,79,83,33,10,82,143.0
99927,G99927,2017-2021,US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,ZCTA5 99927,15,10,10,10,10,10,15,NaN
99929,G99929,2017-2021,US,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,938.0,ZCTA5 99929,71,107,107,106,26,10,116,18.0

In [8]:
stats_df["UR"] = df["AOSJE005"] / df["AOSJE002"]
stats_df["Rent"] = df["AOT9E001"]
stats_df

,Min Share,Black Share,White Share,Asian Share,Hisp Share,Native Share,W_Avg Emp Min Share,W_Avg Emp Black Share,W_Avg Emp White Share,W_Avg Emp Asian Share,...,Loans per Emp Bus_3,Avg Loan Amt per Emp_3,Rural,Avg Loan Amt per Emp_2 Adj,Avg Loan Amt per Emp_3 Adj,Census Region,PC Inc,Gini,UR,Rent
ZIP,,,,,,,,,,,,,,,,,,,,,
01001,0.153910,0.020784,0.001354,0.028910,0.067711,0.846090,0.104759,0.018225,0.799004,NaN,...,0.239583,1601.181785,0.009656,984.395315,1964.191364,Northeast,41144.0,0.4284,0.053640,1208.0
01002,0.367189,0.050403,0.001669,0.157123,0.099028,0.632811,NaN,NaN,0.801804,NaN,...,0.221269,1381.447152,0.149721,1482.744737,1694.639916,Northeast,38627.0,0.5444,0.069994,1342.0
01003,0.395684,0.066249,0.001056,0.201766,0.087376,0.604316,0.069946,NaN,0.792399,0.044714,...,0.000000,0.000000,0.000000,0.000000,0.000000,Northeast,4935.0,0.5023,0.188624,NaN
01005,0.090816,0.009388,0.001429,0.006122,0.031224,0.909184,0.094359,0.008223,0.831570,0.069017,...,0.125786,1318.133737,1.000000,768.233646,1616.972493,Northeast,39783.0,0.3377,0.041595,NaN
01007,0.133113,0.017441,0.000389,0.023796,0.042793,0.866887,0.069946,NaN,0.792399,0.044714,...,0.185668,2044.624220,0.719704,2020.545932,2508.168199,Northeast,43450.0,0.3815,0.024678,1110.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99923,0.106061,0.000000,0.000000,0.000000,0.030303,0.893939,NaN,NaN,0.800000,NaN,...,0.000000,0.000000,1.000000,541.346591,0.000000,West,NaN,NaN,0.000000,NaN
99925,0.626276,0.005102,0.440051,0.010204,0.017857,0.373724,NaN,NaN,0.800000,NaN,...,0.166667,2622.490040,1.000000,2002.704694,3217.044021,West,30746.0,0.4480,0.103158,794.0
99926,0.903329,0.002561,0.743278,0.000000,0.029449,0.096671,NaN,NaN,0.800000,NaN,...,0.000000,0.000000,1.000000,977.071691,0.000000,West,24979.0,0.3818,0.158879,600.0
99927,0.142857,0.000000,0.000000,0.000000,0.040816,0.857143,NaN,NaN,0.800000,NaN,...,NaN,NaN,1.000000,NaN,NaN,West,NaN,NaN,NaN,NaN
99929,0.364598,0.000000,0.173641,0.012025,0.036075,0.635402,NaN,NaN,0.810526,NaN,...,0.652632,4324.713376,1.000000,1679.179493,5305.184422,West,31080.0,0.4146,0.057108,938.0

In [9]:
dummies = pd.get_dummies(stats_df['Census Region'])
stats_df = pd.concat([stats_df, dummies], axis=1)
stats_df

,Min Share,Black Share,White Share,Asian Share,Hisp Share,Native Share,W_Avg Emp Min Share,W_Avg Emp Black Share,W_Avg Emp White Share,W_Avg Emp Asian Share,...,Avg Loan Amt per Emp_3 Adj,Census Region,PC Inc,Gini,UR,Rent,Midwest,Northeast,South,West
ZIP,,,,,,,,,,,,,,,,,,,,,
01001,0.153910,0.020784,0.001354,0.028910,0.067711,0.846090,0.104759,0.018225,0.799004,NaN,...,1964.191364,Northeast,41144.0,0.4284,0.053640,1208.0,0,1,0,0
01002,0.367189,0.050403,0.001669,0.157123,0.099028,0.632811,NaN,NaN,0.801804,NaN,...,1694.639916,Northeast,38627.0,0.5444,0.069994,1342.0,0,1,0,0
01003,0.395684,0.066249,0.001056,0.201766,0.087376,0.604316,0.069946,NaN,0.792399,0.044714,...,0.000000,Northeast,4935.0,0.5023,0.188624,NaN,0,1,0,0
01005,0.090816,0.009388,0.001429,0.006122,0.031224,0.909184,0.094359,0.008223,0.831570,0.069017,...,1616.972493,Northeast,39783.0,0.3377,0.041595,NaN,0,1,0,0
01007,0.133113,0.017441,0.000389,0.023796,0.042793,0.866887,0.069946,NaN,0.792399,0.044714,...,2508.168199,Northeast,43450.0,0.3815,0.024678,1110.0,0,1,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99923,0.106061,0.000000,0.000000,0.000000,0.030303,0.893939,NaN,NaN,0.800000,NaN,...,0.000000,West,NaN,NaN,0.000000,NaN,0,0,0,1
99925,0.626276,0.005102,0.440051,0.010204,0.017857,0.373724,NaN,NaN,0.800000,NaN,...,3217.044021,West,30746.0,0.4480,0.103158,794.0,0,0,0,1
99926,0.903329,0.002561,0.743278,0.000000,0.029449,0.096671,NaN,NaN,0.800000,NaN,...,0.000000,West,24979.0,0.3818,0.158879,600.0,0,0,0,1
99927,0.142857,0.000000,0.000000,0.000000,0.040816,0.857143,NaN,NaN,0.800000,NaN,...,NaN,West,NaN,NaN,NaN,NaN,0,0,0,1
99929,0.364598,0.000000,0.173641,0.012025,0.036075,0.635402,NaN,NaN,0.810526,NaN,...,5305.184422,West,31080.0,0.4146,0.057108,938.0,0,0,0,1

In [10]:
reg_df = stats_df[["Min Share", "Black Share", "Rural", 
                   "Midwest", "Northeast", "South", 
                   "PC Inc", "Gini", "UR", "Rent", 
                   "Loans per Emp Bus_1", "Loans per Emp Bus_2",
                   "Loans per Emp Bus_3", 'Avg Loan Amt per Emp_1', 
                   'Avg Loan Amt per Emp_2','Avg Loan Amt per Emp_3',
                   'Avg Loan Amt per Emp_2 Adj',
                   'Avg Loan Amt per Emp_3 Adj']].dropna()
reg_df

,Min Share,Black Share,Rural,Midwest,Northeast,South,PC Inc,Gini,UR,Rent,Loans per Emp Bus_1,Loans per Emp Bus_2,Loans per Emp Bus_3,Avg Loan Amt per Emp_1,Avg Loan Amt per Emp_2,Avg Loan Amt per Emp_3,Avg Loan Amt per Emp_2 Adj,Avg Loan Amt per Emp_3 Adj
ZIP,,,,,,,,,,,,,,,,,,
01001,0.153910,0.020784,0.009656,0,1,0,41144.0,0.4284,0.053640,1208.0,0.245833,0.245833,0.239583,3352.367207,902.597423,1601.181785,984.395315,1964.191364
01002,0.367189,0.050403,0.149721,0,1,0,38627.0,0.5444,0.069994,1342.0,0.145798,0.202401,0.221269,1715.197631,1359.536721,1381.447152,1482.744737,1694.639916
01007,0.133113,0.017441,0.719704,0,1,0,43450.0,0.3815,0.024678,1110.0,0.175896,0.172638,0.185668,2655.974900,1852.649565,2044.624220,2020.545932,2508.168199
01008,0.061503,0.000000,1.000000,0,1,0,43288.0,0.3648,0.013136,820.0,0.055556,0.055556,0.074074,465.515789,588.680702,797.628070,642.029890,978.461148
01010,0.104015,0.007276,1.000000,0,1,0,45461.0,0.4655,0.057205,825.0,0.093750,0.164062,0.171875,1628.207343,1345.907127,2494.734341,1467.879961,3060.324376
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99921,0.313038,0.002460,1.000000,0,0,0,37841.0,0.4226,0.056859,880.0,0.097222,0.333333,0.347222,1865.935056,2362.244477,6164.665857,2576.322882,7562.279031
99922,0.934211,0.002632,1.000000,0,0,0,21621.0,0.4263,0.111940,667.0,0.000000,0.333333,0.166667,0.000000,2242.167407,231.481481,2445.363829,283.961466
99925,0.626276,0.005102,1.000000,0,0,0,30746.0,0.4480,0.103158,794.0,0.066667,0.100000,0.166667,1121.355378,1836.290837,2622.490040,2002.704694,3217.044021
99926,0.903329,0.002561,1.000000,0,0,0,24979.0,0.3818,0.158879,600.0,0.000000,0.083333,0.000000,0.000000,895.882353,0.000000,977.071691,0.000000
99929,0.364598,0.000000,1.000000,0,0,0,31080.0,0.4146,0.057108,938.0,0.294737,0.284211,0.652632,1062.297637,1539.648819,4324.713376,1679.179493,5305.184422

In [11]:
reg_df.describe()

,Min Share,Black Share,Rural,Midwest,Northeast,South,PC Inc,Gini,UR,Rent,Loans per Emp Bus_1,Loans per Emp Bus_2,Loans per Emp Bus_3,Avg Loan Amt per Emp_1,Avg Loan Amt per Emp_2,Avg Loan Amt per Emp_3,Avg Loan Amt per Emp_2 Adj,Avg Loan Amt per Emp_3 Adj
count,25725.000000,25725.000000,25725.000000,25725.000000,25725.000000,25725.000000,25725.000000,25725.000000,25725.000000,25725.000000,25725.000000,25725.000000,25725.000000,25725.000000,25725.000000,25725.000000,25725.000000,25725.000000
mean,0.274581,0.080080,0.577337,0.315024,0.185967,0.333800,34786.146006,0.424842,0.052922,1009.949310,0.117444,0.169558,0.180570,3000.097227,1647.780199,2344.429894,1797.110280,2875.943877
std,0.245089,0.151631,0.448971,0.464535,0.389088,0.471578,15136.739471,0.060638,0.040919,443.179258,0.079227,0.125870,0.120532,4281.763808,2435.875602,3871.622332,2656.626829,4749.371508
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3292.000000,0.043200,0.000000,99.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.083272,0.003876,0.031166,0.000000,0.000000,0.000000,25868.000000,0.386600,0.028512,717.000000,0.058333,0.070423,0.092308,1245.988593,557.995017,967.344838,608.563315,1186.655004
50%,0.181034,0.013790,0.904931,0.000000,0.000000,0.000000,31412.000000,0.421900,0.045353,877.000000,0.105528,0.137931,0.162162,2247.630640,1128.740799,1623.129190,1231.032934,1991.114543
75%,0.395499,0.076912,1.000000,1.000000,0.000000,1.000000,39255.000000,0.460300,0.067418,1179.000000,0.165217,0.250000,0.250000,3626.405257,2023.120649,2667.130633,2206.465958,3271.805241
max,0.998473,0.971768,1.000000,1.000000,1.000000,1.000000,252645.000000,0.787200,1.000000,3501.000000,1.400000,1.250000,2.090909,285900.000000,98409.090909,225840.500000,107327.414773,277041.597540

In [12]:
from scipy import stats
alpha = 0.05  # significance level
for col in reg_df.columns:
    stat, p = stats.shapiro(reg_df[col])
    if p < alpha:
        print(f"{col} is not normally distributed (p={p:.4f})")
    else:
        print(f"{col} is normally distributed (p={p:.4f})")

Min Share is not normally distributed (p=0.0000)
Black Share is not normally distributed (p=0.0000)
Rural is not normally distributed (p=0.0000)
Midwest is not normally distributed (p=0.0000)
Northeast is not normally distributed (p=0.0000)
South is not normally distributed (p=0.0000)
PC Inc is not normally distributed (p=0.0000)
Gini is not normally distributed (p=0.0000)
UR is not normally distributed (p=0.0000)
Rent is not normally distributed (p=0.0000)
Loans per Emp Bus_1 is not normally distributed (p=0.0000)
Loans per Emp Bus_2 is not normally distributed (p=0.0000)
Loans per Emp Bus_3 is not normally distributed (p=0.0000)
Avg Loan Amt per Emp_1 is not normally distributed (p=0.0000)
Avg Loan Amt per Emp_2 is not normally distributed (p=0.0000)
Avg Loan Amt per Emp_3 is not normally distributed (p=0.0000)
Avg Loan Amt per Emp_2 Adj is not normally distributed (p=0.0000)
Avg Loan Amt per Emp_3 Adj is not normally distributed (p=0.0000)

C:\Users\hthog\anaconda3\lib\site-packages\scipy\stats\_morestats.py:1800: UserWarning: p-value may not be accurate for N > 5000.
  warnings.warn("p-value may not be accurate for N > 5000.")

In [13]:
for col in reg_df.columns:
    stat, p = stats.shapiro(np.log(reg_df[col]))
    if p < alpha:
        print(f"{col} is not normally distributed (p={p:.4f})")
    else:
        print(f"{col} is normally distributed (p={p:.4f})")

Min Share is normally distributed (p=1.0000)
Black Share is normally distributed (p=1.0000)
Rural is normally distributed (p=1.0000)
Midwest is normally distributed (p=1.0000)
Northeast is normally distributed (p=1.0000)
South is normally distributed (p=1.0000)
PC Inc is not normally distributed (p=0.0000)
Gini is not normally distributed (p=0.0000)
UR is normally distributed (p=1.0000)
Rent is not normally distributed (p=0.0000)
Loans per Emp Bus_1 is normally distributed (p=1.0000)
Loans per Emp Bus_2 is normally distributed (p=1.0000)
Loans per Emp Bus_3 is normally distributed (p=1.0000)
Avg Loan Amt per Emp_1 is normally distributed (p=1.0000)
Avg Loan Amt per Emp_2 is normally distributed (p=1.0000)
Avg Loan Amt per Emp_3 is normally distributed (p=1.0000)
Avg Loan Amt per Emp_2 Adj is normally distributed (p=1.0000)
Avg Loan Amt per Emp_3 Adj is normally distributed (p=1.0000)

C:\Users\hthog\anaconda3\lib\site-packages\pandas\core\arraylike.py:402: RuntimeWarning: divide by zero encountered in log
  result = getattr(ufunc, method)(*inputs, **kwargs)
C:\Users\hthog\anaconda3\lib\site-packages\scipy\stats\_morestats.py:1789: RuntimeWarning: invalid value encountered in subtract
  x = x - np.median(x)

In [14]:
reg_df[["Min Share", "Black Share", "Rural", "UR", "Loans per Emp Bus_1", "Loans per Emp Bus_2",
                   "Loans per Emp Bus_3", 'Avg Loan Amt per Emp_1', 
                   'Avg Loan Amt per Emp_2','Avg Loan Amt per Emp_3',
                   'Avg Loan Amt per Emp_2 Adj',
                   'Avg Loan Amt per Emp_3 Adj']] = reg_df[["Min Share", "Black Share", "Rural", "UR", "Loans per Emp Bus_1", "Loans per Emp Bus_2",
                   "Loans per Emp Bus_3", 'Avg Loan Amt per Emp_1', 
                   'Avg Loan Amt per Emp_2','Avg Loan Amt per Emp_3',
                   'Avg Loan Amt per Emp_2 Adj',
                   'Avg Loan Amt per Emp_3 Adj']].applymap(lambda x: np.log(x) if x > 0 else np.nan)

In [15]:
reg_df = reg_df.dropna()
reg_df

,Min Share,Black Share,Rural,Midwest,Northeast,South,PC Inc,Gini,UR,Rent,Loans per Emp Bus_1,Loans per Emp Bus_2,Loans per Emp Bus_3,Avg Loan Amt per Emp_1,Avg Loan Amt per Emp_2,Avg Loan Amt per Emp_3,Avg Loan Amt per Emp_2 Adj,Avg Loan Amt per Emp_3 Adj
ZIP,,,,,,,,,,,,,,,,,,
01001,-1.871390,-3.873559,-4.640161,0,1,0,41144.0,0.4284,-2.925463,1208.0,-1.403101,-1.403101,-1.428854,8.117422,6.805277,7.378497,6.892028,7.582836
01002,-1.001878,-2.987709,-1.898984,0,1,0,38627.0,0.5444,-2.659351,1342.0,-1.925536,-1.597503,-1.508375,7.447284,7.214899,7.230887,7.301650,7.435226
01007,-2.016558,-4.048904,-0.328915,0,1,0,43450.0,0.3815,-3.701863,1110.0,-1.737864,-1.756556,-1.683796,7.884567,7.524372,7.622969,7.611123,7.827308
01010,-2.263219,-4.923220,0.000000,0,1,0,45461.0,0.4655,-2.861122,825.0,-2.367124,-1.807508,-1.760988,7.395235,7.204824,7.821938,7.291574,8.026276
01026,-2.407836,-5.532401,0.000000,0,1,0,37484.0,0.4028,-4.037186,938.0,-3.218876,-2.525729,-2.525729,4.682368,5.484661,5.295162,5.571412,5.499500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99840,-1.907931,-5.331107,0.000000,0,0,0,43562.0,0.3576,-2.050089,1071.0,-1.882731,-0.995428,-0.609766,8.766071,8.646591,9.932750,8.733341,10.137089
99901,-0.889889,-4.937491,-1.958396,0,0,0,40538.0,0.4317,-3.080508,1235.0,-1.477586,-1.619556,-0.992078,8.147478,7.707895,8.589930,7.794646,8.794269
99919,-1.711567,-5.145555,0.000000,0,0,0,28310.0,0.4492,-3.202746,870.0,-2.251292,-2.251292,-1.845827,7.531395,6.591466,8.207685,6.678217,8.412023
99921,-1.161430,-6.007584,0.000000,0,0,0,37841.0,0.4226,-2.867177,880.0,-2.330756,-1.098612,-1.057790,7.531518,7.767367,8.726589,7.854118,8.930928
99925,-0.467965,-5.278115,0.000000,0,0,0,30746.0,0.4480,-2.271495,794.0,-2.708050,-2.302585,-1.791759,7.022293,7.515503,7.871880,7.602254,8.076218

In [16]:
from statsmodels.stats.outliers_influence import variance_inflation_factor
vif_data = pd.Series([variance_inflation_factor(reg_df.values, i) for i in range(reg_df.shape[1])], index=reg_df.columns)
print("VIF for each variable:")
print(vif_data)

VIF for each variable:
Min Share                     3.056080
Black Share                   2.924990
Rural                         1.810638
Midwest                       3.717716
Northeast                     2.636786
South                         3.675167
PC Inc                        2.604785
Gini                          1.300347
UR                            1.204689
Rent                          3.030018
Loans per Emp Bus_1           3.240726
Loans per Emp Bus_2           5.081914
Loans per Emp Bus_3           5.186761
Avg Loan Amt per Emp_1        2.155467
Avg Loan Amt per Emp_2             inf
Avg Loan Amt per Emp_3             inf
Avg Loan Amt per Emp_2 Adj         inf
Avg Loan Amt per Emp_3 Adj         inf
dtype: float64

C:\Users\hthog\anaconda3\lib\site-packages\statsmodels\stats\outliers_influence.py:195: RuntimeWarning: divide by zero encountered in double_scalars
  vif = 1. / (1. - r_squared_i)

In [17]:
X = reg_df[["Min Share", "Black Share", "Rural", "Midwest", "Northeast", "South", "PC Inc", "Gini", "UR", "Rent"]]
X = sm.add_constant(X)
y = reg_df["Loans per Emp Bus_1"]
model = sm.OLS(y, X)
results = model.fit(cov_type = 'HC3')
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                             OLS Regression Results
===============================================================================
Dep. Variable:     Loans per Emp Bus_1   R-squared:                       0.201
Model:                             OLS   Adj. R-squared:                  0.201
Method:                  Least Squares   F-statistic:                     445.4
Date:                 Mon, 25 Sep 2023   Prob (F-statistic):               0.00
Time:                         10:00:52   Log-Likelihood:                -17761.
No. Observations:                17797   AIC:                         3.554e+04
Df Residuals:                    17786   BIC:                         3.563e+04
Df Model:                           10
Covariance Type:                   HC3
===============================================================================
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
const          -2.8587      0.068    -41.933      0.000      -2.992      -2.725
Min Share       0.0320      0.011      2.822      0.005       0.010       0.054
Black Share     0.0706      0.005     14.192      0.000       0.061       0.080
Rural          -0.1044      0.003    -30.461      0.000      -0.111      -0.098
Midwest         0.3552      0.021     16.965      0.000       0.314       0.396
Northeast       0.5135      0.021     23.910      0.000       0.471       0.556
South           0.0925      0.021      4.458      0.000       0.052       0.133
PC Inc       1.451e-05   7.15e-07     20.310      0.000    1.31e-05    1.59e-05
Gini            0.2846      0.113      2.516      0.012       0.063       0.506
UR             -0.0502      0.009     -5.837      0.000      -0.067      -0.033
Rent           -0.0003   2.32e-05    -10.954      0.000      -0.000      -0.000
==============================================================================
Omnibus:                     1497.997   Durbin-Watson:                   1.525
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             2105.497
Skew:                          -0.692   Prob(JB):                         0.00
Kurtosis:                       3.962   Cond. No.                     8.44e+05
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The condition number is large, 8.44e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [18]:
X = reg_df[["Min Share", "Black Share", "Rural", "Midwest", "Northeast", "South", "PC Inc", "Gini", "UR", "Rent"]]
X = sm.add_constant(X)
y = reg_df["Loans per Emp Bus_2"]
model = sm.OLS(y, X)
results = model.fit(cov_type = 'HC3')
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                             OLS Regression Results
===============================================================================
Dep. Variable:     Loans per Emp Bus_2   R-squared:                       0.462
Model:                             OLS   Adj. R-squared:                  0.461
Method:                  Least Squares   F-statistic:                     1382.
Date:                 Mon, 25 Sep 2023   Prob (F-statistic):               0.00
Time:                         10:00:52   Log-Likelihood:                -15324.
No. Observations:                17797   AIC:                         3.067e+04
Df Residuals:                    17786   BIC:                         3.075e+04
Df Model:                           10
Covariance Type:                   HC3
===============================================================================
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
const          -2.0696      0.059    -34.940      0.000      -2.186      -1.953
Min Share       0.0261      0.010      2.519      0.012       0.006       0.046
Black Share     0.1098      0.005     23.109      0.000       0.100       0.119
Rural          -0.1150      0.003    -39.635      0.000      -0.121      -0.109
Midwest        -0.2067      0.017    -12.432      0.000      -0.239      -0.174
Northeast       0.0270      0.017      1.591      0.112      -0.006       0.060
South          -0.2811      0.017    -16.090      0.000      -0.315      -0.247
PC Inc        1.55e-05   6.51e-07     23.811      0.000    1.42e-05    1.68e-05
Gini           -0.4835      0.097     -4.986      0.000      -0.674      -0.293
UR              0.0614      0.007      8.219      0.000       0.047       0.076
Rent            0.0003   2.12e-05     16.366      0.000       0.000       0.000
==============================================================================
Omnibus:                     1899.712   Durbin-Watson:                   1.462
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3273.596
Skew:                          -0.743   Prob(JB):                         0.00
Kurtosis:                       4.486   Cond. No.                     8.44e+05
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The condition number is large, 8.44e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [19]:
X = reg_df[["Min Share", "Black Share", "Rural", "Midwest", "Northeast", "South", "PC Inc", "Gini", "UR", "Rent"]]
X = sm.add_constant(X)
y = reg_df["Loans per Emp Bus_3"]
model = sm.OLS(y, X)
results = model.fit(cov_type = 'HC3')
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                             OLS Regression Results
===============================================================================
Dep. Variable:     Loans per Emp Bus_3   R-squared:                       0.372
Model:                             OLS   Adj. R-squared:                  0.372
Method:                  Least Squares   F-statistic:                     1045.
Date:                 Mon, 25 Sep 2023   Prob (F-statistic):               0.00
Time:                         10:00:52   Log-Likelihood:                -13714.
No. Observations:                17797   AIC:                         2.745e+04
Df Residuals:                    17786   BIC:                         2.754e+04
Df Model:                           10
Covariance Type:                   HC3
===============================================================================
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
const          -2.1146      0.055    -38.231      0.000      -2.223      -2.006
Min Share       0.0792      0.010      8.323      0.000       0.061       0.098
Black Share     0.0952      0.004     22.190      0.000       0.087       0.104
Rural          -0.0958      0.003    -36.446      0.000      -0.101      -0.091
Midwest         0.2009      0.015     13.005      0.000       0.171       0.231
Northeast       0.2701      0.016     17.071      0.000       0.239       0.301
South          -0.0935      0.016     -5.891      0.000      -0.125      -0.062
PC Inc        1.38e-05   5.75e-07     23.991      0.000    1.27e-05    1.49e-05
Gini           -0.2050      0.091     -2.253      0.024      -0.383      -0.027
UR              0.0060      0.007      0.883      0.377      -0.007       0.019
Rent            0.0001   1.89e-05      6.717      0.000    8.98e-05       0.000
==============================================================================
Omnibus:                     2351.782   Durbin-Watson:                   1.517
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             5648.336
Skew:                          -0.768   Prob(JB):                         0.00
Kurtosis:                       5.292   Cond. No.                     8.44e+05
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The condition number is large, 8.44e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [20]:
X = reg_df[["Min Share", "Black Share", "Rural", "Midwest", "Northeast", "South", "PC Inc", "Gini", "UR", "Rent"]]
X = sm.add_constant(X)
y = reg_df['Avg Loan Amt per Emp_1']
model = sm.OLS(y, X)
results = model.fit(cov_type = 'HC3')
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                              OLS Regression Results
==================================================================================
Dep. Variable:     Avg Loan Amt per Emp_1   R-squared:                       0.066
Model:                                OLS   Adj. R-squared:                  0.066
Method:                     Least Squares   F-statistic:                     116.8
Date:                    Mon, 25 Sep 2023   Prob (F-statistic):          1.03e-236
Time:                            10:00:52   Log-Likelihood:                -22873.
No. Observations:                   17797   AIC:                         4.577e+04
Df Residuals:                       17786   BIC:                         4.585e+04
Df Model:                              10
Covariance Type:                      HC3
===============================================================================
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
const           7.0081      0.095     73.896      0.000       6.822       7.194
Min Share       0.0394      0.016      2.532      0.011       0.009       0.070
Black Share    -0.0472      0.007     -6.817      0.000      -0.061      -0.034
Rural           0.0123      0.004      2.772      0.006       0.004       0.021
Midwest         0.4307      0.028     15.222      0.000       0.375       0.486
Northeast       0.3463      0.029     11.860      0.000       0.289       0.404
South           0.2761      0.028      9.936      0.000       0.222       0.331
PC Inc       1.113e-05      1e-06     11.134      0.000    9.17e-06    1.31e-05
Gini           -0.6173      0.154     -4.009      0.000      -0.919      -0.316
UR             -0.0943      0.012     -8.112      0.000      -0.117      -0.071
Rent           -0.0001   3.38e-05     -4.141      0.000      -0.000   -7.37e-05
==============================================================================
Omnibus:                     3696.957   Durbin-Watson:                   1.866
Prob(Omnibus):                  0.000   Jarque-Bera (JB):            13959.975
Skew:                          -1.004   Prob(JB):                         0.00
Kurtosis:                       6.846   Cond. No.                     8.44e+05
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The condition number is large, 8.44e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [21]:
X = reg_df[["Min Share", "Black Share", "Rural", "Midwest", "Northeast", "South", "PC Inc", "Gini", "UR", "Rent"]]
X = sm.add_constant(X)
y = reg_df['Avg Loan Amt per Emp_2']
model = sm.OLS(y, X)
results = model.fit(cov_type = 'HC3')
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                              OLS Regression Results
==================================================================================
Dep. Variable:     Avg Loan Amt per Emp_2   R-squared:                       0.123
Model:                                OLS   Adj. R-squared:                  0.122
Method:                     Least Squares   F-statistic:                     272.1
Date:                    Mon, 25 Sep 2023   Prob (F-statistic):               0.00
Time:                            10:00:53   Log-Likelihood:                -23643.
No. Observations:                   17797   AIC:                         4.731e+04
Df Residuals:                       17786   BIC:                         4.739e+04
Df Model:                              10
Covariance Type:                      HC3
===============================================================================
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
const           7.2038      0.096     75.422      0.000       7.017       7.391
Min Share       0.0627      0.016      3.799      0.000       0.030       0.095
Black Share    -0.0255      0.007     -3.478      0.001      -0.040      -0.011
Rural           0.0521      0.004     11.682      0.000       0.043       0.061
Midwest        -0.4517      0.027    -16.591      0.000      -0.505      -0.398
Northeast      -0.3423      0.028    -12.321      0.000      -0.397      -0.288
South          -0.3130      0.027    -11.755      0.000      -0.365      -0.261
PC Inc       1.365e-05    9.4e-07     14.518      0.000    1.18e-05    1.55e-05
Gini           -1.3896      0.159     -8.754      0.000      -1.701      -1.078
UR              0.0494      0.013      3.944      0.000       0.025       0.074
Rent            0.0004   3.29e-05     11.957      0.000       0.000       0.000
==============================================================================
Omnibus:                     1588.794   Durbin-Watson:                   1.791
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             4471.668
Skew:                          -0.494   Prob(JB):                         0.00
Kurtosis:                       5.248   Cond. No.                     8.44e+05
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The condition number is large, 8.44e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [22]:
X = reg_df[["Min Share", "Black Share", "Rural", "Midwest", "Northeast", "South", "PC Inc", "Gini", "UR", "Rent"]]
X = sm.add_constant(X)
y = reg_df['Avg Loan Amt per Emp_3']
model = sm.OLS(y, X)
results = model.fit(cov_type = 'HC3')
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                              OLS Regression Results
==================================================================================
Dep. Variable:     Avg Loan Amt per Emp_3   R-squared:                       0.069
Model:                                OLS   Adj. R-squared:                  0.068
Method:                     Least Squares   F-statistic:                     145.5
Date:                    Mon, 25 Sep 2023   Prob (F-statistic):          1.60e-294
Time:                            10:00:53   Log-Likelihood:                -21878.
No. Observations:                   17797   AIC:                         4.378e+04
Df Residuals:                       17786   BIC:                         4.386e+04
Df Model:                              10
Covariance Type:                      HC3
===============================================================================
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
const           6.9981      0.091     77.231      0.000       6.820       7.176
Min Share       0.0897      0.015      6.008      0.000       0.060       0.119
Black Share    -0.0601      0.007     -8.952      0.000      -0.073      -0.047
Rural           0.0552      0.004     13.562      0.000       0.047       0.063
Midwest         0.1086      0.026      4.248      0.000       0.059       0.159
Northeast       0.1091      0.026      4.194      0.000       0.058       0.160
South           0.0360      0.025      1.448      0.148      -0.013       0.085
PC Inc       1.318e-05   8.34e-07     15.800      0.000    1.15e-05    1.48e-05
Gini           -0.8623      0.149     -5.780      0.000      -1.155      -0.570
UR             -0.0206      0.011     -1.812      0.070      -0.043       0.002
Rent            0.0001   2.93e-05      4.362      0.000    7.04e-05       0.000
==============================================================================
Omnibus:                     1917.094   Durbin-Watson:                   1.846
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             7332.193
Skew:                          -0.501   Prob(JB):                         0.00
Kurtosis:                       5.980   Cond. No.                     8.44e+05
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The condition number is large, 8.44e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [23]:
X = reg_df[["Min Share", "Black Share", "Rural", "Midwest", "Northeast", "South", "PC Inc", "Gini", "UR", "Rent"]]
X = sm.add_constant(X)
y = reg_df['Avg Loan Amt per Emp_2 Adj']
model = sm.OLS(y, X)
results = model.fit(cov_type = 'HC3')
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                OLS Regression Results
======================================================================================
Dep. Variable:     Avg Loan Amt per Emp_2 Adj   R-squared:                       0.123
Model:                                    OLS   Adj. R-squared:                  0.122
Method:                         Least Squares   F-statistic:                     272.1
Date:                        Mon, 25 Sep 2023   Prob (F-statistic):               0.00
Time:                                10:00:53   Log-Likelihood:                -23643.
No. Observations:                       17797   AIC:                         4.731e+04
Df Residuals:                           17786   BIC:                         4.739e+04
Df Model:                                  10
Covariance Type:                          HC3
===============================================================================
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
const           7.2906      0.096     76.331      0.000       7.103       7.478
Min Share       0.0627      0.016      3.799      0.000       0.030       0.095
Black Share    -0.0255      0.007     -3.478      0.001      -0.040      -0.011
Rural           0.0521      0.004     11.682      0.000       0.043       0.061
Midwest        -0.4517      0.027    -16.591      0.000      -0.505      -0.398
Northeast      -0.3423      0.028    -12.321      0.000      -0.397      -0.288
South          -0.3130      0.027    -11.755      0.000      -0.365      -0.261
PC Inc       1.365e-05    9.4e-07     14.518      0.000    1.18e-05    1.55e-05
Gini           -1.3896      0.159     -8.754      0.000      -1.701      -1.078
UR              0.0494      0.013      3.944      0.000       0.025       0.074
Rent            0.0004   3.29e-05     11.957      0.000       0.000       0.000
==============================================================================
Omnibus:                     1588.794   Durbin-Watson:                   1.791
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             4471.668
Skew:                          -0.494   Prob(JB):                         0.00
Kurtosis:                       5.248   Cond. No.                     8.44e+05
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The condition number is large, 8.44e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [24]:
X = reg_df[["Min Share", "Black Share", "Rural", "Midwest", "Northeast", "South", "PC Inc", "Gini", "UR", "Rent"]]
X = sm.add_constant(X)
y = reg_df['Avg Loan Amt per Emp_3 Adj']
model = sm.OLS(y, X)
results = model.fit(cov_type = 'HC3')
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                OLS Regression Results
======================================================================================
Dep. Variable:     Avg Loan Amt per Emp_3 Adj   R-squared:                       0.069
Model:                                    OLS   Adj. R-squared:                  0.068
Method:                         Least Squares   F-statistic:                     145.5
Date:                        Mon, 25 Sep 2023   Prob (F-statistic):          1.60e-294
Time:                                10:00:53   Log-Likelihood:                -21878.
No. Observations:                       17797   AIC:                         4.378e+04
Df Residuals:                           17786   BIC:                         4.386e+04
Df Model:                                  10
Covariance Type:                          HC3
===============================================================================
                  coef    std err          z      P>|z|      [0.025      0.975]
-------------------------------------------------------------------------------
const           7.2024      0.091     79.486      0.000       7.025       7.380
Min Share       0.0897      0.015      6.008      0.000       0.060       0.119
Black Share    -0.0601      0.007     -8.952      0.000      -0.073      -0.047
Rural           0.0552      0.004     13.562      0.000       0.047       0.063
Midwest         0.1086      0.026      4.248      0.000       0.059       0.159
Northeast       0.1091      0.026      4.194      0.000       0.058       0.160
South           0.0360      0.025      1.448      0.148      -0.013       0.085
PC Inc       1.318e-05   8.34e-07     15.800      0.000    1.15e-05    1.48e-05
Gini           -0.8623      0.149     -5.780      0.000      -1.155      -0.570
UR             -0.0206      0.011     -1.812      0.070      -0.043       0.002
Rent            0.0001   2.93e-05      4.362      0.000    7.04e-05       0.000
==============================================================================
Omnibus:                     1917.094   Durbin-Watson:                   1.846
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             7332.193
Skew:                          -0.501   Prob(JB):                         0.00
Kurtosis:                       5.980   Cond. No.                     8.44e+05
==============================================================================

Notes:
[1] Standard Errors are heteroscedasticity robust (HC3)
[2] The condition number is large, 8.44e+05. This might indicate that there are
strong multicollinearity or other numerical problems.
"""

In [32]:
results.HC3_se

const          9.061199e-02
Min Share      1.493336e-02
Black Share    6.708793e-03
Rural          4.073321e-03
Midwest        2.557164e-02
Northeast      2.601826e-02
South          2.483099e-02
PC Inc         8.344354e-07
Gini           1.491775e-01
UR             1.138396e-02
Rent           2.930991e-05
dtype: float64

In [44]:
df = pd.DataFrame(results.params)
df["Pvalues"] = results.pvalues
df["std error"] = results.HC3_se
df["Stars"] = df["Pvalues"].apply(lambda x: "***" if x < 0.01 else ("**" if x < 0.05 else ("*" if x < 0.1 else ""))) 
df["Final"] = df[0].round(3).astype(str) + df["Stars"] + " [" + df["std error"].round(3).astype(str) + "]"
df["Final"]

const           7.202*** [0.091]
Min Share        0.09*** [0.015]
Black Share     -0.06*** [0.007]
Rural           0.055*** [0.004]
Midwest         0.109*** [0.026]
Northeast       0.109*** [0.026]
South              0.036 [0.025]
PC Inc              0.0*** [0.0]
Gini           -0.862*** [0.149]
UR               -0.021* [0.011]
Rent                0.0*** [0.0]
Name: Final, dtype: object